CREATE TABLE IF NOT EXISTS books
(
	ID int(11) AUTO_INCREMENT NOT NULL,
	TITLE int(11) NOT NULL,
	AUTHOR varchar(255) NOT NULL,
	RATING INT(11) NOT NULL,
	PAGES INT(11) NOT NULL,
	DESCRIPTION TEXT NOT NULL,

	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS authors
(
	ID int(11) AUTO_INCREMENT NOT NULL,
	NAME int(11) NOT NULL,

	PRIMARY KEY (ID)
);

